// <auto-generated />
using System;
using FWA_Stations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FWA_Stations.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260218123945_UpdatePermissionsEntity2")]
    partial class UpdatePermissionsEntity2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FWA_Stations.Entities.ErrorLogs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("delete_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("delete_user_id")
                        .HasColumnType("int");

                    b.Property<string>("details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("entity_id")
                        .HasColumnType("int");

                    b.Property<string>("entity_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insert_user_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("operation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("update_user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("delete_user_id");

                    b.HasIndex("insert_user_id");

                    b.HasIndex("update_user_id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Permissions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("order")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Stations", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("delete_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("delete_user_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insert_user_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("update_user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("delete_user_id");

                    b.HasIndex("insert_user_id");

                    b.HasIndex("update_user_id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Subscribers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("delete_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("delete_user_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insert_user_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("line_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link_mac_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("management_ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("management_vlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mikrotik_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mikrotik_mac_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("odf_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("odf_port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sas_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sas_port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("service_type")
                        .HasColumnType("int");

                    b.Property<int>("station_id")
                        .HasColumnType("int");

                    b.Property<string>("unit_direction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("unit_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("update_user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("delete_user_id");

                    b.HasIndex("insert_user_id");

                    b.HasIndex("station_id");

                    b.HasIndex("update_user_id");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("FWA_Stations.Entities.UserPermissions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("permission_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("permission_id");

                    b.HasIndex("user_id");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("delete_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("delete_user_id")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insert_user_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("update_user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("delete_user_id");

                    b.HasIndex("insert_user_id");

                    b.HasIndex("update_user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Warehouse", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("assigned_user_id")
                        .HasColumnType("int");

                    b.Property<string>("customer_line_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("delete_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("delete_user_id")
                        .HasColumnType("int");

                    b.Property<string>("destination_location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("device_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("insert_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("insert_user_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_delete")
                        .HasColumnType("bit");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serial_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source_location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("update_user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("assigned_user_id");

                    b.HasIndex("delete_user_id");

                    b.HasIndex("insert_user_id");

                    b.HasIndex("update_user_id");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("FWA_Stations.Entities.ErrorLogs", b =>
                {
                    b.HasOne("FWA_Stations.Entities.Users", "delete_user")
                        .WithMany()
                        .HasForeignKey("delete_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Users", "insert_user")
                        .WithMany()
                        .HasForeignKey("insert_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Users", "update_user")
                        .WithMany()
                        .HasForeignKey("update_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("delete_user");

                    b.Navigation("insert_user");

                    b.Navigation("update_user");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Stations", b =>
                {
                    b.HasOne("FWA_Stations.Entities.Users", "delete_user")
                        .WithMany()
                        .HasForeignKey("delete_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Users", "insert_user")
                        .WithMany()
                        .HasForeignKey("insert_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Users", "update_user")
                        .WithMany()
                        .HasForeignKey("update_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("delete_user");

                    b.Navigation("insert_user");

                    b.Navigation("update_user");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Subscribers", b =>
                {
                    b.HasOne("FWA_Stations.Entities.Users", "delete_user")
                        .WithMany()
                        .HasForeignKey("delete_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Users", "insert_user")
                        .WithMany()
                        .HasForeignKey("insert_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Stations", "station")
                        .WithMany("subscribers")
                        .HasForeignKey("station_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FWA_Stations.Entities.Users", "update_user")
                        .WithMany()
                        .HasForeignKey("update_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("delete_user");

                    b.Navigation("insert_user");

                    b.Navigation("station");

                    b.Navigation("update_user");
                });

            modelBuilder.Entity("FWA_Stations.Entities.UserPermissions", b =>
                {
                    b.HasOne("FWA_Stations.Entities.Permissions", "permission")
                        .WithMany("user_permissions")
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FWA_Stations.Entities.Users", "user")
                        .WithMany("user_permissions")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("user");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Users", b =>
                {
                    b.HasOne("FWA_Stations.Entities.Users", "delete_user")
                        .WithMany()
                        .HasForeignKey("delete_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Users", "insert_user")
                        .WithMany()
                        .HasForeignKey("insert_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Users", "update_user")
                        .WithMany()
                        .HasForeignKey("update_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("delete_user");

                    b.Navigation("insert_user");

                    b.Navigation("update_user");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Warehouse", b =>
                {
                    b.HasOne("FWA_Stations.Entities.Users", "assigned_user")
                        .WithMany()
                        .HasForeignKey("assigned_user_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FWA_Stations.Entities.Users", "delete_user")
                        .WithMany()
                        .HasForeignKey("delete_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Users", "insert_user")
                        .WithMany()
                        .HasForeignKey("insert_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FWA_Stations.Entities.Users", "update_user")
                        .WithMany()
                        .HasForeignKey("update_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("assigned_user");

                    b.Navigation("delete_user");

                    b.Navigation("insert_user");

                    b.Navigation("update_user");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Permissions", b =>
                {
                    b.Navigation("user_permissions");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Stations", b =>
                {
                    b.Navigation("subscribers");
                });

            modelBuilder.Entity("FWA_Stations.Entities.Users", b =>
                {
                    b.Navigation("user_permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
